node{
    stage('Cloning'){
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'github access', url: 'https://github.com/aditya-tanwar/jenkins-simple-java-maven-app.git']]])
    }
    stage('Build'){
        tool 'maven'
        sh 'mvn clean install'
    }
    stage('Hello'){
        echo 'Hello world!'
    }
}
